version: "3.8"

services:
  php:
    # container_name: flask
    # build: 
    #   context: .
    #   dockerfile: dockerfile
    image: php_apache
    networks:
      - demo-network
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - ./public:/var/www/html
  mysql:
    image: mysql:5.7
    networks:
      - demo-network
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  phpmyadmin:
    image: phpmyadmin:5.2.0
    networks:
      - demo-network
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      
networks:
  demo-network:
