FROM php:7.4.30-apache


RUN apt-get update && \
    docker-php-ext-install mysqli pdo pdo_mysql && \  
    docker-php-ext-enable pdo_mysql


# COPY ../public/index.php /var/www/html/

WORKDIR /var/www/html/

# VOLUME ["/app"]

EXPOSE 80

# exec command
# docker container run -d -p 80:80 --rm -v $(pwd):/var/www/html php-apache